# Generated by Django 3.0.6 on 2020-05-31 14:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 14, 43, 34, 937075, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 14, 43, 34, 937075, tzinfo=utc)),
        ),
    ]
