# Generated by Django 3.0.6 on 2020-05-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200531_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_on',
        ),
    ]
