# Generated by Django 3.0.6 on 2020-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='section_texts',
            field=models.TextField(default='none'),
        ),
    ]
