# Generated by Django 3.0.6 on 2020-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_section_texts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
