# Generated by Django 3.0.6 on 2020-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_tag_slug'),
        ('projects', '0011_auto_20200603_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
