# Generated by Django 3.0.6 on 2020-06-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200612_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags_as_str',
            field=models.CharField(default='default_tags_as_str', max_length=500),
        ),
    ]
