# Generated by Django 3.0.6 on 2020-06-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='section_texts',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_intro',
            field=models.TextField(default='default short intro'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='default_tag', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='default content'),
        ),
    ]
