# Generated by Django 3.0.6 on 2020-06-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200603_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technologies',
            field=models.CharField(default='default_technology', max_length=300),
        ),
    ]
