# Generated by Django 3.0.6 on 2020-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug_name',
            field=models.SlugField(default=''),
        ),
    ]
