# Generated by Django 3.0.6 on 2020-06-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag_slug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
