# Generated by Django 3.0.6 on 2020-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200615_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_readtime',
            field=models.CharField(default='no readtime estimate', max_length=100),
        ),
    ]
