# Generated by Django 3.0.6 on 2020-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_source',
            field=models.CharField(default='default_image_source', max_length=300),
        ),
    ]
