# Generated by Django 3.0.6 on 2020-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(default='test_from_email', max_length=300)),
                ('subject', models.CharField(default='test_subject', max_length=3000)),
                ('message', models.TextField()),
            ],
        ),
    ]
