# Generated by Django 3.0.6 on 2020-05-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default='test_name', max_length=300),
        ),
    ]
