# Generated by Django 3.0.6 on 2020-05-26 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_contactmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
