# Generated by Django 3.0.6 on 2020-05-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
