# Generated by Django 3.0.6 on 2020-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_file_name', max_length=200)),
                ('pdf', models.FileField(upload_to='pdf')),
            ],
        ),
    ]
