# Generated by Django 3.0.6 on 2020-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_filepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepdf',
            name='identifier',
            field=models.CharField(default='default_file_identifier', max_length=200),
        ),
    ]
